name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install && mkdir -p ./bin

      - run: npm run package

      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ./bin/omni.vsix
